name: Android Kernel Xiaomi Ginkgo

on:
  push:
    branches: [ Q ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  ginkgo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Updating Libraries
      run: |
        sudo apt-get update -y && sudo apt-get upgrade -y 
        sudo apt-get install -y make clang bash g++ gcc cmake build-essential

    - name: Testing Build
      timeout-minutes: 320
      continue-on-error: true
      run: |
        sudo bash build.sh
        sudo bash build1.sh
