name: Android Kernel Xiaomi Ginkgo

on:
  push:
    branches: [ Q ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  wbb:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Testing
      run: |
        sudo apt-get update -y && sudo apt-get install bash
        sudo bash build.sh
